### ISSUE TITLE
在 svg-path-commander 2.0 中，lineToCubic更新为了一个更简单的算法

### ISSUE THREAD

**Issue by entronad** [antvis/util#102]
在 svg-path-commander 2.0 中，lineToCubic更新为了一个更简单的算法：
https://github.com/thednp/svg-path-commander/commit/175770255f06628d61b6dbd96e8fbc8a0a6ee228#diff-a7563e18ea440e76d4aa2b638cd044a860e08c1e297ddbc8745fdc296d808e82

现在这个算法我觉得挺合理的，因为事先不知道line变成cubic后要去变换成的曲线是什么样子的，所以事先去精细的计算两个控制点的分位似乎没必要是一种过度优化，只要在线段上就行了（各在1/3, 2/3分位似乎也挺好？）

老实说，它之前那个算法为什么要大费周章从p0算到p6的我不太理解，而且传入segmentLineFactory的参数数目都对不上（我看到你们截取了前面几个数目对上了，但似乎含义还是对不上）

**Comment by entronad** [comment]
作者说原先那个是错的：
https://github.com/thednp/svg-path-commander/issues/25

**Comment by xiaoiver** [comment]
v3.3.4 is published.
