### ISSUE TITLE
'@antv/dom-util@*' is not in this registry.

### ISSUE THREAD

**Issue by manojbavikati** [antvis/util#105]
ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@antv%2fdom-util - Not found
npm ERR! 404
npm ERR! 404  '@antv/dom-util@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by xiaoiver** [comment]
We move it to v2 legacy branch:
https://github.com/antvis/util/tree/v2/packages/dom-util
