### ISSUE TITLE
3.3.9版本存在重大bug

### ISSUE THREAD

**Issue by dodospace** [antvis/util#120]
2024.9.19日发布时候，发现当前库更新了3.3.9版本，在安装的时候无法安装

npm ERR! code 127
npm ERR! path /Users/admin/fe-cn/old-version/case-page/node_modules/@antv/util
npm ERR! command failed
npm ERR! command sh -c husky install
npm ERR! sh: husky: command not found

排查看了3.3.9版本，在安装的时候执行了postinstall，然后package.json里删除了husky运行命令，导致安装包一直无法安装，目前发布停滞了近1个小时

**Comment by davidlevi7** [comment]
Also have this issue `"postinstall": "husky install",`

**Comment by Aarebecca** [comment]
3.3.10 已修复
