### ISSUE TITLE
@antv/matrix-util 升级

### ISSUE THREAD

**Issue by dengfuping** [antvis/util#46]
- 根据 #45，@antv/matrix-util 在 `^3.1.0-beta.1` 版本后的引入方式发生变化，属于不兼容性变更，需要上层依赖 @antv/matrix-util 的库手动升级到 `^3.1.0-beta.1`，并修改对应的引入方式，测试通过后发布一个 bugfix 版本。
    - [x] [Component](https://github.com/antvis/component) @simaQ  
    - [x] [coord](https://github.com/antvis/coord) @simaQ  
    - [x] [G2](https://github.com/antvis/G2) @simaQ 
    - [x] [G2Plot](https://github.com/antvis/G2Plot) @paleface001 
    - [x] [@antv/coord](https://github.com/antvis/coord) @simaQ 
    - [ ] [G6](https://github.com/antvis/G6) @baizn 
    - [x] [G](https://github.com/antvis/g) @dengfuping

**Comment by simaQ** [comment]
component 我来吧，我已经改了

**Comment by xinyu198736** [comment]
哪个版本里有 transform 这个方法鸭
