### ISSUE TITLE
哪里可以找到util.js文件？where can i find util.js?

### ISSUE THREAD

**Issue by czppaa** [antvis/util#48]
在网上没有找到util.js。 我不熟悉npm，现在通过cnpm下载了util包在本地。我希望能把这个包变成util.js,以便可以在html中通过<script>引入，应该怎么做？

以及所有的需要@antv/。。引入的模块的js版本在哪里可以找到？

**Comment by hustcc** [comment]
util 没有 umd 包，不建议只用 antv/util，建议直接使用 lodash。

**Comment by czppaa** [comment]
> util 没有 umd 包，不建议只用 antv/util，建议直接使用 lodash。

感谢，已经转战echarts了
