### ISSUE TITLE
index.d.ts中未导出min、max的定义

### ISSUE THREAD

**Issue by muyoulongjingcha** [antvis/util#62]
如下图所示，在g-base中使用了max、min方法，但是在util中未导出其定义
![Snipaste_2021-05-11_23-31-34](https://user-images.githubusercontent.com/20529682/117844266-1f100b00-b2b2-11eb-9172-0704c1715407.png)
因此，渲染图形时报`TypeError: Object(...) is not a function`错误
![Snipaste_2021-05-11_23-43-16](https://user-images.githubusercontent.com/20529682/117845237-f1779180-b2b2-11eb-8185-54ccb2001057.png)
![image](https://user-images.githubusercontent.com/20529682/117845420-19ff8b80-b2b3-11eb-8e1d-48e69ba7d775.png)

**Comment by visiky** [comment]
重新安装依赖，检查下自己安装的版本

**Comment by visiky** [comment]
related: https://github.com/ant-design/ant-design-charts/issues/587

**Comment by muyoulongjingcha** [comment]
删除lock文件，删除node_modules，重新安装后可以了。
我是使用G2间接依赖的util，只升级G2版本，npm install没有更新util的依赖，导致的此问题。

**Comment by muyoulongjingcha** [comment]
删除lock文件，删除node_modules，重新安装后可以了。
我是使用G2间接依赖的util，只升级G2版本，npm install没有更新util的依赖，导致的此问题。
