### ISSUE TITLE
钉钉工作台组件 引入 @antv/f2-my 打包报错 @antv/util/lib/type/is-nil未找到

### ISSUE THREAD

**Issue by xiaoyierle** [antvis/util#79]
具体版本号  "@antv/f2-my": "^4.0.19"

钉钉工作台组件 引入 @antv/f2-my 打包报错 @antv/util/lib/type/is-nil未找到，请检查package.json配置

在使用F2的时候，报找不到依赖的问题，跟这个库有关吗？
./plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib/stack.js
@antv/util/lib/type/is-nil未找到，请检查package.json配置，并尝试重新安装node_modules依赖

./plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib/symmetric.js
@antv/util/lib/type/is-array未找到，请检查package.json配置，并尝试重新安装node_modules依赖

./plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib/symmetric.js
@antv/util/lib/math/max-by未找到，请检查package.json配置，并尝试重新安装node_modules依赖

**Comment by xiaoyierle** [comment]
./plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib/symmetric.js
@antv/util/lib/array/merge未找到，请检查package.json配置，并尝试重新安装node_modules依赖
Module+not+found:+Can't+resolve+'@antv/util/lib/array/merge'+in+'/tmp/data/build/plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib'
-------------
./plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib/symmetric.js
@antv/util/lib/math/max-by未找到，请检查package.json配置，并尝试重新安装node_modules依赖
Module+not+found:+Can't+resolve+'@antv/util/lib/math/max-by'+in+'/tmp/data/build/plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib'
-------------
./plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib/stack.js
@antv/util/lib/type/is-array未找到，请检查package.json配置，并尝试重新安装node_modules依赖
Module+not+found:+Can't+resolve+'@antv/util/lib/type/is-array'+in+'/tmp/data/build/plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib'
-------------
./plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib/symmetric.js
@antv/util/lib/type/is-array未找到，请检查package.json配置，并尝试重新安装node_modules依赖
Module+not+found:+Can't+resolve+'@antv/util/lib/type/is-array'+in+'/tmp/data/build/plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib'
-------------
./plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib/stack.js
@antv/util/lib/type/is-nil未找到，请检查package.json配置，并尝试重新安装node_modules依赖
Module+not+found:+Can't+resolve+'@antv/util/lib/type/is-nil'+in+'/tmp/data/build/plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib'
-------------
index.worker.js+from+UglifyJs
Unexpected+token:+operator+«*

**Comment by xiaoyierle** [comment]
./plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib/symmetric.js
@antv/util/lib/array/merge未找到，请检查package.json配置，并尝试重新安装node_modules依赖
Module+not+found:+Can't+resolve+'@antv/util/lib/array/merge'+in+'/tmp/data/build/plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib'

./plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib/symmetric.js
@antv/util/lib/math/max-by未找到，请检查package.json配置，并尝试重新安装node_modules依赖
Module+not+found:+Can't+resolve+'@antv/util/lib/math/max-by'+in+'/tmp/data/build/plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib'

./plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib/stack.js
@antv/util/lib/type/is-array未找到，请检查package.json配置，并尝试重新安装node_modules依赖
Module+not+found:+Can't+resolve+'@antv/util/lib/type/is-array'+in+'/tmp/data/build/plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib'

./plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib/symmetric.js
@antv/util/lib/type/is-array未找到，请检查package.json配置，并尝试重新安装node_modules依赖
Module+not+found:+Can't+resolve+'@antv/util/lib/type/is-array'+in+'/tmp/data/build/plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib'

./plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib/stack.js
@antv/util/lib/type/is-nil未找到，请检查package.json配置，并尝试重新安装node_modules依赖
Module+not+found:+Can't+resolve+'@antv/util/lib/type/is-nil'+in+'/tmp/data/build/plugin/node_modules/@antv/f2/node_modules/@antv/adjust/lib'

index.worker.js+from+UglifyJs
Unexpected+token:+operator+«*

**Comment by xiaoiver** [comment]
@zengyue 有空能帮忙看看嘛

**Comment by xiaoyierle** [comment]
这个问题应该在 antv 处理掉了，我把这个关掉～
